# ruby encoding: utf-8
CarType.create("name"=>"3er", "wikipedia_url"=>"")
CarType.create("name"=>"5er", "wikipedia_url"=>"")
CarType.create("name"=>"1er", "wikipedia_url"=>"")
CarBodyStyle.create("name"=>"Cabrio", "wikipedia_url"=>"")
CarBodyStyle.create("name"=>"Roadster", "wikipedia_url"=>"")
CarBodyStyle.create("name"=>"Limousine (3-tuerig)", "wikipedia_url"=>"")
CarBodyStyle.create("name"=>"Limousine (4-tuerig)", "wikipedia_url"=>"")
CarBodyStyle.create("name"=>"Limousine (5-tuerig)", "wikipedia_url"=>"")
CarBodyStyle.create("name"=>"Coupe", "wikipedia_url"=>"")
CarBodyStyle.create("name"=>"Kombi", "wikipedia_url"=>"")
confi = CarConfiguration.find_or_create_by_car_type_id_and_car_body_style_id("1", "4")
Assembly.create(facility_id: 1, car_configuration_id: confi.id)
confi = CarConfiguration.find_or_create_by_car_type_id_and_car_body_style_id("1", "7")
Assembly.create(facility_id: 1, car_configuration_id: confi.id)
confi = CarConfiguration.find_or_create_by_car_type_id_and_car_body_style_id("2", "4")
Assembly.create(facility_id: 2, car_configuration_id: confi.id)
confi = CarConfiguration.find_or_create_by_car_type_id_and_car_body_style_id("2", "7")
Assembly.create(facility_id: 2, car_configuration_id: confi.id)
Company.create("image_url"=>"bmw.png", "name"=>"BMW", "wikipedia_url"=>"http://de.wikipedia.org/wiki/BMW").facilities.create([{"address"=>"Dostlerstr. 1, 80809 Munich", "latitude"=>48.17717, "longitude"=>11.56332, "name"=>"Werk 1.1", "wikipedia_url"=>"http://de.wikipedia.org/wiki/BMW-Werk_M%C3%BCnchen"},{"address"=>"Landshuter Strasse 56,  84130 Dingolfing", "latitude"=>48.64932, "longitude"=>12.47142, "name"=>"Werk 2", "wikipedia_url"=>"http://de.wikipedia.org/wiki/"},{"address"=>"Ohmstraße 2,  84030 Landshut", "latitude"=>48.55893, "longitude"=>12.14871, "name"=>"Werk 4.1", "wikipedia_url"=>"http://de.wikipedia.org/wiki/BMW-Werk_Landshut"}])
Company.create("image_url"=>"audi.png", "name"=>"Audi", "wikipedia_url"=>"http://de.wikipedia.org/wiki/Audi").facilities.create([{"address"=>"Ettinger Straße, 85057 Ingolstadt", "latitude"=>48.77802000000001, "longitude"=>11.41544, "name"=>"Werk 1", "wikipedia_url"=>"http://de.wikipedia.org/wiki/"}])
Company.create("image_url"=>"mercedes.png", "name"=>"Mercedes", "wikipedia_url"=>"http://de.wikipedia.org/wiki/Mercedes-Benz_Cars").facilities.create([{"address"=>"Mercedesstraße 137, 70327 Stuttgart", "latitude"=>48.7854787, "longitude"=>9.2411403, "name"=>"Werk Untertürkheim", "wikipedia_url"=>"http://de.wikipedia.org/wiki/Mercedes-Benz_Cars#Mercedes-Benz-Werk_in_Stuttgart-Untert.C3.BCrkheim"},{"address"=>"Bela-Barenyi-Straße, 71063 Sindelfingen", "latitude"=>48.70426, "longitude"=>8.99339, "name"=>"Werk Sindelfingen", "wikipedia_url"=>"http://de.wikipedia.org/wiki/"},{"address"=>"Mercedesstraße 1, 28309 Bremen", "latitude"=>53.05401, "longitude"=>8.9062, "name"=>"Werk Bremen", "wikipedia_url"=>"http://de.wikipedia.org/wiki/"}])
